### PR TITLE
Add player_monoids support

### PR DESCRIPTION
**Pull request by Niklp09**
Much simpler #17 to have a chance this gets merged soon.

- Remove deprecated depends.text & description.txt
- Add player_monoids support for sitting
- Add player_monoids to mod dependencies

### CODE REVIEW

**Review by SmallJoker — APPROVED** [review]
Technically speaking, the dependency is not needed at all. `minetest.get_modpath` can also be used on mods that are yet not loaded.

LGTM. Will merge in a few days unless there are objections.

**Comment by Niklp09** [comment]
> Technically speaking, the dependency is not needed at all. minetest.get_modpath can also be used on mods that are yet not loaded.

But it's helpful to see which mods support `player_monoids` w/o reading (or grepping) the code.

**Comment by SmallJoker** [comment]
Yes, it is helpful up to the point when there's circular dependencies. In either case, I suppose this is yet not a problem.

**Review by Thomas--S — APPROVED** [review]
I didn't test it, but the code and the concept looks good to me :+1:

**Pull request merged**
