### PR TITLE
L10n support Pt1

### PR DESCRIPTION
**Pull request by ghost**
Added localization support.
NOTE: The source code needs further modifications due to [how MT Engine's L10n works](https://github.com/minetest/minetest/blob/76325d0ba925cfdd18e387ae96d27921136e98e5/doc/lua_api.txt#L2459).

So far it would display, e.g.:
Material + Object ---> [ENG] Wooden + Chair [OK] ---> [ITA] di legno + sedia [WRONG]
Italian, French, etc. descriptions must be "Object" + "Material".

Since I'm not a programmer I didn't touched the items registrations code; this commit isn't properly solving the localization issue but it's a start.

### CODE REVIEW

**Comment by Thomas--S** [comment]
Thanks for this PR. I really appreciate the work you do for translating Minetest and its mods.

I will take a look at the code soon to see how we can solve the problem you mentioned.

**Comment by ghost** [comment]
Thanks :)

**Comment by Thomas--S** [comment]
Oh, I completely forgot about this.

I'll try to care about the l10n support as soon as I have time for this.

Thanks for reminding me.

**Comment by Thomas--S** [comment]
Thanks for your patience. I finally managed to implement l10n support in a way that solves the problems you mentioned in your first post.
I greatly appreciate your contribution!

**Comment by ghost** [comment]
> Thanks for your patience. I finally managed to implement l10n support in a way that solves the problems you mentioned in your first post.
> I greatly appreciate your contribution!

:) You're welcome, I've just opened a PR; thanks for this nice mod!

**Pull request closed without merging**
